version: '3.1'
services:
  stats-service:
    build: stats/stats-service
    image: stats-service-image
    container_name: stats-service-container
    ports:
      - "9090:9090"
    depends_on:
     -  stats-db
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-service
    - SPRING_DATASOURCE_USERNAME=root
    - SPRING_DATASOURCE_PASSWORD=root
    - SPRING_DRIVER_CLASS_NAME=org.postgresql.Driver

  stats-db:
    image: postgres:14-alpine
    container_name: db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats-service
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
